name: .NET Tests and Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/CongestionTaxApp/CongestionTaxApp.csproj

    - name: Clean and Build
      run: |
        dotnet clean ./src/CongestionTaxApp/CongestionTaxApp.csproj
        dotnet build ./src/CongestionTaxApp/CongestionTaxApp.csproj --configuration Release

    - name: Run Tests
      run: dotnet test ./tests/CongestionTaxApp.Tests/CongestionTaxApp.Tests.csproj --configuration Release --logger "console;verbosity=error"

    - name: Publish
      run: dotnet publish ./src/CongestionTaxApp/CongestionTaxApp.csproj --configuration Release --output ./publish
